spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
server:
  port : 8090